name: 'Clevertec Frontend Marathon Check Tests Action'
description: 'Send tests result to server'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pull_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  host:
    description: 'The host of the server'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'